# Generated by Django 2.1.2 on 2018-11-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=14)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
