# Generated by Django 2.1.5 on 2019-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancerApp', '0004_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
