# Generated by Django 2.1.5 on 2019-03-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancerApp', '0005_auto_20190304_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='patient_id',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
