# Generated by Django 2.2.2 on 2019-06-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancerApp', '0007_auto_20190605_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.TextField(),
        ),
    ]
